class Invoices::Form < ApplicationForm
  def view_template(&)
    row field(:customer_id).select(Customer.by_tenant.order(name: :asc).select(:id, :name), prompt: I18n.t(".select_customer"), class: "mort-form-select")
    # row field(:project_id).select(Project.by_tenant.by_customer().order(name: :asc).select(:id, :name), prompt: I18n.t(".select_project"), class: "mort-form-select")
    row field(:invoice_number).input().focus
    row field(:currency).input()
    row field(:invoice_number).input()
    row field(:currency).input()
    row field(:state).input()
    row field(:mail_out_state).input()
    row field(:latest_mail_out_type).input()
    row field(:locale).input()
    row field(:external_reference).input()
    row field(:description).input()
    row field(:comment).input()
    row field(:invoice_date).input()
    row field(:payment_date).input()
    row field(:address).input()
    row field(:erp_guid).input()
    row field(:show_lines_incl_vat).input()
    row field(:invoice_template_id).input()
    row field(:contact_guid).input()
    row field(:payment_condition_number_of_days).input()
    row field(:payment_condition_type).input()
    row field(:reminder_fee).input()
    row field(:reminder_interest_rate).input()
    row field(:total_excl_vat_in_dkk).input()
    row field(:total_excl_vat).input()
    row field(:total_incl_vat_in_dkk).input()
    row field(:total_incl_vat).input()
    row field(:is_mobile_pay_invoice_enabled).boolean(class: "mort-form-text")
    row field(:is_penso_pay_enabled).boolean(class: "mort-form-text")
  end
end
