class Invoices::Form < ApplicationForm
  def view_template(&)
    row field(:customer_id).select(Customer.by_tenant.order(name: :asc).select(:id, :name), prompt: I18n.t(".select_customer"), class: "mort-form-text")
    # row field(:project_id).select(Project.by_tenant.by_customer().order(name: :asc).select(:id, :name), prompt: I18n.t(".select_project"), class: "mort-form-text")
    row field(:invoice_number).input(class: "mort-form-text").focus
    row field(:currency).input(class: "mort-form-text")
    row field(:invoice_number).input(class: "mort-form-text")
    row field(:currency).input(class: "mort-form-text")
    row field(:state).input(class: "mort-form-text")
    row field(:mail_out_state).input(class: "mort-form-text")
    row field(:latest_mail_out_type).input(class: "mort-form-text")
    row field(:locale).input(class: "mort-form-text")
    row field(:external_reference).input(class: "mort-form-text")
    row field(:description).input(class: "mort-form-text")
    row field(:comment).input(class: "mort-form-text")
    row field(:invoice_date).input(class: "mort-form-text")
    row field(:payment_date).input(class: "mort-form-text")
    row field(:address).input(class: "mort-form-text")
    row field(:erp_guid).input(class: "mort-form-text")
    row field(:show_lines_incl_vat).input(class: "mort-form-text")
    row field(:invoice_template_id).input(class: "mort-form-text")
    row field(:contact_guid).input(class: "mort-form-text")
    row field(:payment_condition_number_of_days).input(class: "mort-form-text")
    row field(:payment_condition_type).input(class: "mort-form-text")
    row field(:reminder_fee).input(class: "mort-form-text")
    row field(:reminder_interest_rate).input(class: "mort-form-text")
    row field(:total_excl_vat_in_dkk).input(class: "mort-form-text")
    row field(:total_excl_vat).input(class: "mort-form-text")
    row field(:total_incl_vat_in_dkk).input(class: "mort-form-text")
    row field(:total_incl_vat).input(class: "mort-form-text")
    row field(:is_mobile_pay_invoice_enabled).boolean(class: "mort-form-text")
    row field(:is_penso_pay_enabled).boolean(class: "mort-form-text")
  end
end
